Repository ssini-oh/futsal-online, pull requests merged in 2024-12, with the labels that each got.

#5 feat : 게임 로직 api 구현
  src/app.js
  src/routes/game.routes.js
Labels: enhancement

#9 feat : 인증 미들웨어 수정 및 game 기능에 인증 추가
  src/middlewares/auth.middleware.js
  src/routes/auth.routes.js
  src/routes/game.routes.js
Labels: bug, enhancement

#15 feat : 보유 카드 조회 및 유저 라우터 연결
  src/app.js
  src/routes/user.routes.js
  src/validations/auth.validation.js
Labels: enhancement

#16 fix : 게임 로직 수정, 유효성 검사 리팩터링, 상태 코드 수정
  src/routes/game.routes.js
Labels: bug, enhancement, refactor

#23 feat: 덱 특정 카드 삭제 api 구현
  prisma/schema.prisma
  src/routes/deck.routes.js
Labels: enhancement
